#ifndef EVENT_H
#define EVENT_H

#include <chrono>
#include <string>

/**
 * @enum EventType
 * @brief defines the categories of signals processed by the DoorAlarmFSM.
 */
enum class EventType
{
    ArmSystem,           ///< Request to transition the system to the Armed state.
    DisarmSystem,        ///< Request to transition the system to the Disarmed state.
    DoorOpened,          ///< Signal from the GPIO reed switch indicating the door is open.
    DoorClosed,          ///< Signal from the GPIO reed switch indicating the door is shut.
    AuthorizedByNfc,     ///< Successful UID validation from the NFC hardware.
    AuthorizedByApp,     ///< Remote authorization signal received via the Web API.
    VerificationTimeout, ///< Internal signal indicating the grace period for entry has expired.
    PrintStatus,         ///< Command to output the current system diagnostic state.
    Shutdown             ///< Signal to terminate all background threads and exit.
};

/**
 * @struct Event
 * @brief A data packet representing a specific occurrence within the system.
 * * Events are generated by hardware threads (NFC, GPIO) or the API thread 
 * and are consumed by the DoorAlarmSystem's control loop.
 */
struct Event
{
    /// The category of the event.
    EventType type;
    
    /// The origin of the event (e.g., "NFC_Reader", "Web_API", "Timer").
    std::string source;
    
    /// The exact wall-clock time when the event was instantiated.
    std::chrono::system_clock::time_point timestamp;

    /**
     * @brief Construct a new Event object.
     * @param t The type of event being created.
     * @param s The source identifier (defaults to "system").
     */
    Event(EventType t, std::string s = "system")
        : type(t), source(std::move(s)), timestamp(std::chrono::system_clock::now())
    {
    }
};

#endif
